#!/bin/bash

# if [ -f ".app_version" ]; then
#     VER=`cat .app_version`
# else
#     VER="1.0.0"
#     echo $VER > .app_version
# fi

# if [ -f ".build_seq" ]; then
#     BLD=`cat .build_seq`
# else
#     BLD='0'
# fi

# ((BLD++))
# echo $BLD > .build_seq
# echo "Ver: $VER ($BLD)" > .current_version

# echo "
# // Auto-generated by updversion.sh. Do not edit.

# class version_buildnumber {
#   static const String name = '$VER';q
#   static const int build = $BLD;
  
# }


# echo "$VER"

# exit 0

java --version
echo 1.what is ur name


echo $(date)
echo $(date +'%d/%m/%Y/%r')
steps:
  - name: Get current time
    uses: josStorer/get-current-time@v2.0.1
    id: current-time
    with:
      format: YYYYMMDD-HH
      utcOffset: "+08:00"
  - name: Use current time
    env:
      TIME: "${{ steps.current-time.outputs.time }}"
      R_TIME: "${{ steps.current-time.outputs.readableTime }}"
      F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
      YEAR: "${{ steps.current-time.outputs.year }}"
      DAY: "${{ steps.current-time.outputs.day }}"
    run: echo $TIME $R_TIME $F_TIME $YEAR $DAY
